language: ruby
services:
- postgresql
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
- cp config/database.travis.yml config/database.yml -f
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rake db:migrate RAILS_ENV=test
- bundle exec rake spec
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: heroku
  api_key:
    secure: jNBHnJnpQBuw5MDGJEM2r2f9RX5eE5JzYJqNjJnoJ0633rzQpAGrNqdS8+YeBpAozI3cGTLVE1/1gGIRiI7nnU6ylLbilTw+cBi6zl0F5zEQqBXbQPUlx57NlPck7eJUcYQkkNpCsgCr6S13mrM8XmZAS2fxsz5zyXjRUeGNMwmCvgrgDjmPH041wYXPAI8IlmXEOFtrL+NxFqQ0OB45UHYKalOerCSHSqkBy2yD9elP8C2UP1p54CVRi6E5/Iv7aKeo9w6qTX3tDV4QWNIZhsgDFYAknvwto3MzI3j2uJsNGVJtPglcp0LGJ4vD3LYkazh4t1v2wYejReVpkcfEH+5L6+JfxnXuWDRKM2pd4XmwSRmpAteiUX1NflfiwtbZQcV6IpqDBPX6LyIEXER6hwEp3IgxQrTGq5cFsiqmIVLVmvCmIyWCPxhGOQwpKyr4HCr6UGcQ+hvC5vDJ+ocNPbTcWpBh1z+T6jVspduR+oLhHdBgAtjwnaKglreYPQt6JknR5JmjM6pTnc/gehoBHWHO7ICp9/WMHkL63nPx9wCD7ZhyO5jFEbVwQYELM+QtD4UC3MEzj5j4+TXl1rA5OMVwzb1j0p0SjFPwAoA5PduZ3llGKDVqRrIyWWamKwXw5giMo2tpNOhS9BRaw1pJy4NODKt35QqJ+0eb8FfCYBk=
  app: waspaid-backend
  on:
    repo: qxlab/waspaid-backend
    branch: master
  run:
  - rake db:migrate
  - rake cleanup
env:
  global:
  - secure: Z/7phpXomgQDNSBG3OcdvN4ztAqKyy1wv1sj3ngn/n4o1BqLJB0T7DvOAKYyCiIkE2McjCQdCijTN7U8ZUPRFZ0ZXcENlSXxT4lhf5mq0lBlhq6xw5ikfLwcw//kEcU+UHjimC7iK0ZUF5Yvt7KEviQu048Ku6PW9lmIp5EMC+sPqeXJ2M6o0aPeyJtc3iOtSy6MahtJ4T0aniw/st4upxnFabQA4A7299Yf7ZJxgTR3La89K2FOJKnPr4tzJWpFE8aXct5dIwK9WgporUUb/czBI67rjKkMSgTv2joEWca91Byrfb/KqxxIc3q8Juypqun2BakDsBxmnxQcPwu9dfQyywdvsYFbgB063st+yf9Z7RelUP6K+GHacLMzur3zmms3BQz3tEiPfQZszEjRnNgo0hL98/ext1m3GR9N7SCCcMdTTokuP6u2hP+3D8WTUbLNTnd9/frmbcY/C2zUbrpXr48nK/2jyJvN4jOfVZUttdv5nf2UelPIbSGUn98Mn1PBF21HHw8dWEhLxwMjECqGX58a7GtuZ2tNFFl24eJ6++Txdni8VUeg/Y5DoPVKU5Kuqn2d9R4svdlj5Xw4PKCUL3Nco11R2EJACN1IRG7R1C7FPwY4WdvbAI2pcD1sy6tmMUR7WKEdbMgjSOrgZFrfTzuOuJzAl/MS+U48Fco=
  - secure: Chely3OZSrV3beLlBTViTDs6z7RdJ1cEwCLdNxQW/ziUbjZD7iY6+wUmeArCb3ofhXSOe6Vfhw7qoSbSZ0By3MOeCjMOblaamqJ6cSCP9YhTd0gqwB2tikBSUl44Wb+dxzJywFpD571TXKFIuYH1USv4KMUiDfAsHQWOBgaeCIz65ZzLWFvQsKJt3BDrxZUCFLAivziIt321IFBHgEBtH2XFXhP5k5cX0zzHjcWRrLGJiox8H8y+DxVuAe5ckVsKidBEC8vjI/QBaVgUphMLXieTsJB0fEtndMBkKOCgVm2DupkayMEv4GJw2XpZtnbMIU/MZzvksIKhMKAX3/Z1ADwotA1uM3T8yZbHIzLz9tpEh++O6I/WwWZo+weFEH/MbO2j26ifJIn/LBMoM/hjiJ7KTMcC4Yc0PhiFETzqW+9l1Ac4XZR+UWUei//F/amD0QIhvPbofqZLC/MrkDeZfebabCAbScsJhdZR06m2Sbrb0rX3WrAcWesH3EHYXaY65fVENbygQ+Sf9OM+7TWdJ/WgX5Bdzz20cIYVw53z8FLLoStYJEBrdMdZOCEdMpXEClpJnmzOnswVmXxH07wzKJ0xdZrKZYnFF2r02TZstncViBxu1SzPz9X5I6pZdaxr9nVpLPmzjdwNPF1PZbTkJG8f9lVbeNOBALoQo5URLJA=
  - secure: D8bngHr3aZVicIMdo85SqcE5bFbJx3iClrJAo3dlPh5xPr1pruxPC4eMdWMyJqgU818dQ/y9G0cvzYMEmlPHF1FRlWPcszIsCyjbShgLQK4IfR4HPEcLjqh80wATVJKxLJPmPjwjy1I0BrdptFKujGefz20/cfl9CPtubpOIoxN9dc6ExXVtMFW2+jbfDw2+8EABHCFl8BuNBd6mxn/Zp6f8o1QmqtAzeVM7c4H0vThOohpLMSIH4KLXEmMsFVV1jselX/DyCqknNm2o2fho9qqcEqDNsPhchc5n3oVgScTew3XMMuYqdtgzUw1TWwHtLxvKmvjHsoacUq93lrrBTVM+deoaplHGDe7BuIPHBbyJF6MEb1zoLUsIaqWZ4Cb25huekqKnIF/VmjzIOqYhCxP1LBwgoZbzI2UwDT37Qntqq5wyrATqYUgOtnUUqtCzdKuqws8+ObYrVQFOqkQ5qz2/gzP0/9E3/0cdwtTYgflVJl3r76CHuuGI9+MEXktteneBLfhHiGwmH+/O506caBuvV7fbkkB6WD1yj5twHTC+YfOf6yckrXvYDRvbXWeiDBrrqdcCBzrX7lNWmBhfO+cAZEcz+WJM0lcABqrrPJHpjexN/dmwhsyf5C4xZ+ICnPdDhLYSZa69r1dSQNS6/9FaecSBRPHlyvJnZjw6UZM=
