default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("RAILS_DB_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("RAILS_DB_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("RAILS_DB_PASSWORD") { 'development' } %>

development:
  <<: *default
  database: waspaid_development

test:
  <<: *default
  database: waspaid_test

production:
  <<: *default
  database: waspaid_production
